apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: gke-workload-metrics
spec:
  selector:
    matchLabels:
      app: gke-workload-metrics
  podMetricsEndpoints:
    - port: web
      path: /metrics
      scheme: http
      interval: 30s
